package main

import "github.com/HeaInSeo/kube-slint/pkg/slo/spec"

type sliSpec = spec.SLISpec

func jumiAHMinimumSpecs() []sliSpec {
	return []sliSpec{
		{ID: "jumi_jobs_created_delta", Title: "JUMI Jobs Created Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how many Kubernetes Jobs JUMI created during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_jobs_created_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_fast_fail_trigger_delta", Title: "JUMI Fast Fail Trigger Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks fast-fail trigger activity while changing JUMI executor behavior.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_fast_fail_trigger_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_artifacts_registered_delta", Title: "JUMI Artifacts Registered Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how many node outputs JUMI published to AH during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_artifacts_registered_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_input_resolve_requests_delta", Title: "JUMI Input Resolve Requests Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how many artifact input resolution requests JUMI issued during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_input_resolve_requests_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_input_remote_fetch_delta", Title: "JUMI Input Remote Fetch Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how often JUMI accepted remote-fetch resolution decisions during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_input_remote_fetch_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_input_materializations_delta", Title: "JUMI Input Materializations Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how many resolved inputs required materialization during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_input_materializations_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_sample_runs_finalized_delta", Title: "JUMI Sample Runs Finalized Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how many sample runs JUMI finalized through AH during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_sample_runs_finalized_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_gc_evaluate_requests_delta", Title: "JUMI GC Evaluate Requests Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how many GC evaluation requests JUMI issued to AH during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_gc_evaluate_requests_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "jumi_cleanup_backlog_objects_end", Title: "JUMI Cleanup Backlog Objects", Unit: "count", Kind: "gauge", Description: "Tracks cleanup debt visible at the end of the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_cleanup_backlog_objects`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeEnd}},
		{ID: "ah_artifacts_registered_delta", Title: "AH Artifacts Registered Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how many artifacts AH accepted into inventory during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_artifacts_registered_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "ah_resolve_requests_delta", Title: "AH Resolve Requests Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks how often JUMI asks AH to resolve a handoff during the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_resolve_requests_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "ah_fallback_delta", Title: "AH Fallback Delta", Unit: "count", Kind: "delta_counter", Description: "Tracks executed fallback transitions inside AH. Planning-mode resolve requests may legitimately leave this at zero even when JUMI accepts a remote_fetch decision.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_fallback_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}},
		{ID: "ah_gc_backlog_bytes_end", Title: "AH GC Backlog Bytes", Unit: "bytes", Kind: "gauge", Description: "Tracks retained backlog visible at the end of the measurement window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_gc_backlog_bytes`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeEnd}},
	}
}

func jumiAHSmokeGuardrailSpecs() []sliSpec {
	return []sliSpec{
		{ID: "jumi_jobs_created_smoke", Title: "JUMI Jobs Created Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should create at least two Jobs for producer and consumer nodes.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_jobs_created_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 2, Level: spec.LevelFail}}}},
		{ID: "jumi_artifacts_registered_smoke", Title: "JUMI Artifacts Registered Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should register at least one producer output through AH.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_artifacts_registered_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "jumi_input_resolve_requests_smoke", Title: "JUMI Input Resolve Requests Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should resolve at least one artifact binding before starting the consumer node.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_input_resolve_requests_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "jumi_input_remote_fetch_smoke", Title: "JUMI Input Remote Fetch Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should observe at least one remote-fetch resolution decision.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_input_remote_fetch_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "jumi_input_materializations_smoke", Title: "JUMI Input Materializations Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should mark at least one resolved input as requiring materialization.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_input_materializations_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "jumi_sample_runs_finalized_smoke", Title: "JUMI Sample Runs Finalized Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should finalize at least one sample run through AH.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_sample_runs_finalized_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "jumi_gc_evaluate_requests_smoke", Title: "JUMI GC Evaluate Requests Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should trigger at least one GC evaluation request.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`jumi_gc_evaluate_requests_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "ah_artifacts_registered_smoke", Title: "AH Artifacts Registered Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should register at least one artifact inside AH inventory.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_artifacts_registered_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "ah_resolve_requests_smoke", Title: "AH Resolve Requests Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run should receive at least one resolve request from JUMI.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_resolve_requests_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 1, Level: spec.LevelFail}}}},
		{ID: "ah_fallback_smoke", Title: "AH Fallback Smoke", Unit: "count", Kind: "delta_counter", Description: "Smoke run records AH executed fallback transitions when resolve happens with a concrete target node. Planning-mode smoke may leave this at zero.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_fallback_total`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeDelta}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpLT, Target: 0, Level: spec.LevelFail}}}},
		{ID: "ah_gc_backlog_bytes_smoke", Title: "AH GC Backlog Bytes Smoke", Unit: "bytes", Kind: "gauge", Description: "Smoke run should not leave non-zero AH GC backlog at the end of the window.", Inputs: []spec.MetricRef{spec.UnsafePromKey(`ah_gc_backlog_bytes`)}, Compute: spec.ComputeSpec{Mode: spec.ComputeEnd}, Judge: &spec.JudgeSpec{Rules: []spec.Rule{{Metric: "value", Op: spec.OpGT, Target: 0, Level: spec.LevelFail}}}},
	}
}
